### ISSUE TITLE
Loosing permissions if using custom command line params

### ISSUE THREAD

**Issue by woozygoozy** [evsar3/sshfs-win-manager#103]
Hi, if I toggle the switch in the advanced tab for the command line params and use the "reconnect" param, I loose the ability to go to the drive - I get an error saying I don't have the permission to do so... removing the param and toggling the switch to the off position causes me to regain access.... what should I do?

**Comment by evsar3** [comment]
Activating the custom command line params, makes the app to clear the defaults options.

This issue has already bring to light here:
https://github.com/evsar3/sshfs-win-manager/issues/89#issuecomment-827917200
