### ISSUE TITLE
feature request: missing mount options 

### ISSUE THREAD

**Issue by Mettwurscht** [evsar3/sshfs-win-manager#11]
It should be possible to use mount options like create_file_umask or create_dir_umask and others.

**Comment by evsar3** [comment]
Hello @Mettwurscht 

For now, the goal is to keep the interface very simple with minimum of configurations. By default the mask is `000` for everything. If you want a more complete application, I highly recommend (SiriKali)[https://github.com/mhogomchungu/sirikali].

Thank you for your suggestion, maybe in version 2.0! :)

**Comment by Atera** [comment]
To be honest, depending on the use case at least umasks might be critical to getting everything to work. One of the main benefits of being able to connect to a server is being able to work with files on the server that are not necessarily owned by the same user (ergo several people share the server). Not being able to set ownership or permissions could be a killer for the usefulness of this. If the matter is keeping the interface simple, by all means allow this to be changed in a config file only advanced users would touch.

**Comment by Mettwurscht** [comment]
Thanks for adding these options now. 👍🏼
