### ISSUE TITLE
Keyfile + password option?

### ISSUE THREAD

**Issue by Stuntaneous** [evsar3/sshfs-win-manager#12]
Is this currently supported? If not, will it be in the future?

**Comment by evsar3** [comment]
Hello @Stuntaneous!
Unfortunately it's not supported yet. There are plans for implementing this feature, but it deppends on some research and spare time, and I don't have any these days.

**Comment by Ogglord** [comment]
@evsar3 what kind of research? Let me know if I can assist with some coding. I would like to stop using SiriKali  as well

**Comment by evsar3** [comment]
Hi @Ogglord,
I need to know if there is any command line option that allow us to pass the key password, if not, what other options are available. Maybe sending to stdin, but how to make sure it's the right time to send the passoword... Stuff like that.

Appreciated your help. Thanks.

**Comment by Leaveyou** [comment]
Hi. Can I help anyhow with this without writing a PR? Like with some investigation? I'm not familiar with this framework or  with vue but would like to help since I'm interested in this feature.

**Comment by evsar3** [comment]
Hi @Leaveyou 

Sure you can! Can you investigate how SiriKali does it?

**Comment by evsar3** [comment]
Hello guys,

I'm afraid that this can't be achived with the current version of SSHFS-Win; I spent all the weekend researching and testing all possible solutions to implement this feature and unfortunally can't made it work.

I will open an issue on SSHFS-Win repository and hope @billziss-gh can get a solution to us for this.

**Comment by evsar3** [comment]
Once that https://github.com/billziss-gh/sshfs-win/issues/217 let it clear that's not possible to use a password protected key, I'm closing this issue.

Better keep looking at #27 for upgrades on using an external key agent for authentication using any key.

**Comment by jo-chemla** [comment]
Hi, jumping into the discussion. Besides using an external key-agent, it could be easier to store encrypted hashes of the passwords in the vuex.json file, which before being sent to sshfs-win fr a connection would be decrypted using the master manager password?

**Comment by evsar3** [comment]
Hello @jo-chemla 

Thank you for your suggestion, however, I think that's better to keep stuff simple, asking for a password every time the program starts is quite annoying.

For those concerning on password storage, there is already in beta versions an authentication method that asks for the password every time it connects to the server.

**Comment by jo-chemla** [comment]
Hi @evsar3 thanks for the quick reply. Indeed, password asked at server connection is already a very step - although a bit long to do if I have 5 servers to reconnect to at each restart. And using an external ssh key agent is another good option, even if it takes longer to implement. Thanks for all your efforts!
