### ISSUE TITLE
Confusing "edit mode" and "delete mode"

### ISSUE THREAD

**Issue by bheorcnh** [evsar3/sshfs-win-manager#137]
In my perception it would be more straight forward to do without that confusing _**usage modes**_ and always display buttons for editing, deleting and connecting, but greying out those control elements which are not available according to the current _**operation mode**_ (connected or not) of the related connection. BTW: Why is _Add Connection_ disabled in edit and delete mode?

**Comment by evsar3** [comment]
This already got my attention before. Such major UI changes fits better in a future v2 of the application.
