### ISSUE TITLE
Error Handling Keyfile Paths with Spaces

### ISSUE THREAD

**Issue by Atera** [evsar3/sshfs-win-manager#14]
Basically I am unable to use sshfs‐win‐manager to connect to a server using a keyfile when the keyfile in question contains a filename (or file path) that contains spaces. Changing the path and filename to a continuous one without spaces fixes the issue, allowing me to connect.

**Comment by evsar3** [comment]
Hello @Atera

Thank you for all your feedback, I read them all!

I guess I'm going to have some spare time this weekend to work in some of the bugs and at least start with the Advanced UI.

This one is actually very easy to fix, I already indentified the problem and fixed.
