### ISSUE TITLE
Connected/Disconnected Status Problems

### ISSUE THREAD

**Issue by Atera** [evsar3/sshfs-win-manager#15]
Seems to be a bug whereby if you connect to a server, and then close out of the program (such as by restarting) the program will still mark the connection as 'connected' and thus be unable to either reconnect or disconnect. Manually editing the veux.json files to mark connections as 'disconnected' fixes the issue.

**Comment by evsar3** [comment]
This issue refers to the same problem on #9

**Comment by Atera** [comment]
Oops, sorry. There aren't that many bugs listed but somehow I managed to overlook #9 . Cheers.
