### ISSUE TITLE
Support for ARM Processors

### ISSUE THREAD

**Issue by DanielSepeur** [evsar3/sshfs-win-manager#155]
Hi,

i work with sshfs-win-manager for a long a time.
Actually i got a new work PC based on an ARM Processor (Ideapad 5G).
Is there a port to a Version for ARM based Windows PCs?

Thanks alot

Daniel

**Comment by evsar3** [comment]
Hello @DanielSepeur,

I'm afraid that I can't make a build for ARM processors right now. I don't have access to a computer with that kind of architecture.

Best
