### ISSUE TITLE
Symlinks Do Not Work

### ISSUE THREAD

**Issue by Atera** [evsar3/sshfs-win-manager#16]
Generally speaking, to keep things simple for users, symlinks should be readable/followed. However, because the follow_symlinks option for SSHFS is not set and because there is no way to set it manually, navigating hosts with symlinks will fail.

**Comment by evsar3** [comment]
This feature can now be achive with the new advanced tab in the connection properties, availabe in [v1.0.2-beta.1](https://github.com/evsar3/sshfs-win-manager/releases/tag/v1.0.2-beta.1) release
