### ISSUE TITLE
Automatically mount when starting, without user input?

### ISSUE THREAD

**Issue by Byproduct** [evsar3/sshfs-win-manager#208]
Thanks for the app, it works nicely!

It autostarts with windows, but the drive I've set up is not mounted until I manually click the green connect icon. Is it possible to connect automatically without any user input? That way I could always have my network drive available in a super convenient way.

**Comment by trinamic-mj** [comment]
Yes, nice app and PW is working fine. Auto connect: see first entry in ADVANCED settings

**Comment by Byproduct** [comment]
Thanks, user error. Somehow managed to not find that menu even though it's clearly there. Sorry! ':D
