### ISSUE TITLE
SSHFS on windows with ProxyCommand (SSH Jump Host)

### ISSUE THREAD

**Issue by gabiknight** [evsar3/sshfs-win-manager#24]
I'm looking for a windows tool that allows me to do sshfs to a server_A that is only accesible from a server_B with public ip. On Ubuntu I use this command:
sshfs -p 22 -oProxyCommand="ssh -W %h:%p user_server_B@ip_server_B"  -o idmap=user -o follow_symlinks user_server_A@ip_server_A:/ /home/USER/destination_folder

ME-----(WAN SSH)-----> Server_B ------(LAN SSH)-------> Server_A

Maybe I can use sshfs-win commands but I don't know how. 
Thank you!

**Comment by evsar3** [comment]
I think this is a question for https://github.com/billziss-gh/sshfs-win
