### ISSUE TITLE
Issue with connecting with key

### ISSUE THREAD

**Issue by hanks42** [evsar3/sshfs-win-manager#30]
Hi I moved my private key used to connect and now when the app starts it keeps trying to connect and never succeeding so I can't edit the connection.

**Comment by unicodepepper** [comment]
I'm having a similar problem - trying to use an encrypted private key just says "connection reset by peer" and does not prompt me for the passphrase at all. What I did to fix it was go to %appdata%/sshfs-win-manager and edit the vuex.json file to change the status to "disconnected", and that way I could remove it with the delete mode inside the app.

**Comment by evsar3** [comment]
Hello,

As described in the project README, this project doesn't support password protected keys yet.

The "forever connecting" issue is a known bug and a temporary workaround for it can be found on issue #9
