### ISSUE TITLE
Keyfile path with a space prevents a connection

### ISSUE THREAD

**Issue by dpurdie** [evsar3/sshfs-win-manager#31]
If the 'KEY FILE" path contains a space then the connection to the host is not made. 
ie: C:\Users\My Name\.ssh\myspecial_id_rsa
Note the 'space' in 'My Name'
The error message is the (very useful) 'Read: Connection reset by peer'

Looking at the command that is sent to the sshfs-win.exe program I see that the -oIdentityFile parameter is surrounded by doble quotes. ie: "-oIdentityFile=C:\\Users\\My Name\\myspecial_id_rsa"

If the identity file does not contain a space, then -oIdentity argument is not quoted.

It gets uglier. Quoting the -oIdentityFile argument requires that any '\\' be replaced with '\\\\'
After randomly typing keys I figured out that the following will work (note use of single and double quotes):

    '-oIdentityFile="C:\\\\Users\\\\My Name\\\\myspecial_id_rsa"'

The path portion is double quoted and the back-slash path separator is replaced by 4 of them
The entire argument is then placed in single quotes.

**Comment by evsar3** [comment]
Hello @dpurdie 

This issue has already ben reported in #14 and fixed on 379e188

It should be present in the next version
