### ISSUE TITLE
Error with object

### ISSUE THREAD

**Issue by seahindeniz** [evsar3/sshfs-win-manager#34]
Hi

I tried to open the app with clicking the tray icon but it has triggered an error message.
![image](https://user-images.githubusercontent.com/5789670/87709892-a3d2eb00-c7ad-11ea-9c78-8bb275616686.png)

I can open the About screen but not the main view.

I have tried to quit and started app from the start menu and it has open with no errors. I think this is a one-time thing but couldn't be sure. So I thought it's best to post this here and may help to find a reason.

I'm using version 1.0.1 on Win 10 2004

**Comment by evsar3** [comment]
This must be an isolated error, since there is no other report on such message before.

**Comment by seahindeniz** [comment]
Sure 👍
