### ISSUE TITLE
Display 'program running in tray' message disable feature

### ISSUE THREAD

**Issue by seahindeniz** [evsar3/sshfs-win-manager#35]
Hi

Whenever I close the app to make it minimize into tray, this notification pops up.
![image](https://user-images.githubusercontent.com/5789670/87710419-6cb10980-c7ae-11ea-9d66-061d8847753b.png)

This is kind of getting annoying after a while because it shows up every time I close the app. I like to inform the app that have learned that it will stay running in the background.

So is it possible to make it hidden after I click the notification to confirm that I have acknowledged?

I'm using version 1.0.1 on Win 10 2004

**Comment by evsar3** [comment]
This message must be shown only once per program lifecycle.
Currently, there is no way to disable it.

**Comment by evsar3** [comment]
This feature is availabe in [v1.0.2-beta.1](https://github.com/evsar3/sshfs-win-manager/releases/tag/v1.0.2-beta.1) release
