### ISSUE TITLE
sshfs-win-manager fails in a non-user-friendly way when sshfs executable is not properly linked

### ISSUE THREAD

**Issue by zardini123** [evsar3/sshfs-win-manager#42]
When setting up sshfs-win-manager, I was getting extremely confused why starting my sshfs mount wasn't working.  When I pressed "connect", it'd throw an error notification of something like "Broken EPIPE" (identical to #17).  After a lot of searching, I realized there was a settings page, and there was a option to choose the sshfs-win executable.

By default, the sshfs-win executable option is pointing to `Program Files`.  My x86 installation of sshfs-win installs to `Program Files (x86)` by default.

My proposal is for the settings button and the sshfs-win option to become red, along with a warning symbol next to it if sshfs-win-manager does not point to an existing file.  This would provide clear indication to users there is an issue that must be addressed.  In addendum, if its possible to throw an error stating "sshfs-win executable not set to an existing file" would be great.

**Comment by evsar3** [comment]
Thank you for quality feedback. I will study a way of implementing such feature.

**Comment by evsar3** [comment]
Fixed in https://github.com/evsar3/sshfs-win-manager/commit/83983a6b9fd310577c082eb657f0ca9132e8bcb7

Your suggestion is pretty good, but for now, I choose to just display an error message to the user when the SSHFS-Win binary is not found.

This fix should be present in next beta release, scheduled for this weekend.

**Comment by evsar3** [comment]
This fix is included in v1.1.0-beta.1 release
