### ISSUE TITLE
Program starts with transparent window.

### ISSUE THREAD

**Issue by dustyraven** [evsar3/sshfs-win-manager#44]
Program starts with transparent window and interface is completely inaccessible.
The icon is on the taskbar, but when I click on it only the window's shadow is shown.
When I put the cursor over transparent/missing window, the cursor starts to blink as the program is very busy.
I've installed the program on 3 PC (1 virtual, 2 physical), this happens to only one of them.

**Comment by evsar3** [comment]
What is the configuration of the computer where this happens?
OS Version?
Screen Resolution?
What virtualization program you are using?

> I've installed the program on 3 PC (1 virtual, 2 physical), this happens to only one of them.

In which one of them this happens? Physical or virtual?

**Comment by dustyraven** [comment]
Physical, Win 10 on some Lenovo workstation

**Comment by evsar3** [comment]
This seems to be an isolated problem. Possible due to a OS configuration.

I will keep this issue open for a while and wait if anyone else also reports this problem.
