### ISSUE TITLE
Debug Log results in immense amount of lag after many debug messages

### ISSUE THREAD

**Issue by zardini123** [evsar3/sshfs-win-manager#45]
After only 20 seconds (of many read requests (or any for that matter)), sshfs-win-manager becomes borderline unresponsive due to having to deal with the insane amount of messages in the debug log.  One can usually get this huge read request count by simply reading a large file.

Suggested fix:  Add a "max debug messages" option in settings that keeps the max messages to a user-definable minimum.  This option **should not** be disable-able.  Instead, users should be given an option to set the max message fairly high, but limit the max so the user doesn't hurt win-managers user experience.  Even on my fairly decent computer, displaying the excessive amount of messages resulted in 20% CPU load with the laggy UI.

Another fix:  Somehow only display and deal with messages that are in the viewport.  I'd recommend the other fix over this one because this doesn't help with insane amount of messages resulting in a super tiny scroll bar.

**Comment by evsar3** [comment]
Thank you for the feedback.

I have also noticed that. And fixed in this commit (https://github.com/evsar3/sshfs-win-manager/commit/b5b63df5a2e6685057dc3172f68f07a0267d95c8)

I just filtered bytes reading and write log messages, those messages doesn't have much usage in debug problems.

**Comment by zardini123** [comment]
Wait, you are now filtering out how many bytes are being read and written?  Why do you consider those message useless?

I was using those messages to see if my options were actually increasing and decreasing the read-write sizes.

I'd very much recommend looking into limiting number of debug messages instead of simply removing messages.  One persons annoying debug message is another persons savior.  If you think majority of people won't use the messages, please add a message filter option, and enable "filter out bytes messages" by default.

**Comment by evsar3** [comment]
This debug is mostly for throbleshooting what is going on, on connecting or disconnecting, for an usage like you want, I recommend digging with command line and redirecting stdout/stderr whatever you want.
Remember: this is a tool for common people to quickly manage they SSHFS connections, not for researching.

Imagine asking someone they debug log for throbleshooting and error and receiving megabytes of data?
This program is meant to just manage connecting and disconnecting from server, what happens between this doesn't matter.

I will consider an option to not filter those messages.

**Comment by zardini123** [comment]
Are you considering filtering number of messages displayed though?  That can be critical regardless of what the message is for reasons explained earlier.

**Comment by evsar3** [comment]
I'm thinking in limiting the output buffer to 16KB regardless of any configuration.
