### ISSUE TITLE
SSHFS-Win-Manager connections show connected

### ISSUE THREAD

**Issue by gnutechie** [evsar3/sshfs-win-manager#47]
Hi there,

SSHFS-Win Manager connections keep showing as connected but actually are not.

I was checking whether the connection will come back up if Windows restarts and I did not disconnenct the SSHFS connection.
Now it's still showing connected and I can't delete it or edit it or even disconnected (even through it's not connected).

Is there a way to reset the manager's entries? For example by deleting a config file that's possibly left over somewhere in the system?

I've tried uninstalling it and re-installing it and it still is present.
Thanks in Advance.

PS: I'm running it on a Windows 10 VM on virt-manager and the host is running Debian Buster 10.5
Hardware is an HP Envy 17 j150ca with 12GBs of RAM and an SSD.

**Comment by evsar3** [comment]
Please see #9
