### ISSUE TITLE
Instruction to run in portable mode

### ISSUE THREAD

**Issue by onlineapps-cloud** [evsar3/sshfs-win-manager#49]
Hi, I want to run your software, but in portable mode, but I have error:
cygfuse: initialization failed: winfsp-x86.dll not found
detailed log:
-----------------------------------------------------
date: 2020-09-27T15:50:16.359Z
conn: {e2c523ec-0706-48a8-bf42-86a0a9700b4e} ()
conntype: password
cmd: "somepath\sshfs-win-3_5_20160-x86\SSHFS-Win\bin\sshfs.exe" ubuntu@someip:/ I: -p22 -ovolname= -odebug -ologlevel=debug1 -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oidmap=user -ouid=-1 -ogid=-1 -oumask=000 -ocreate_umask=000 -omax_readahead=1GB -oallow_other -olarge_read -okernel_cache -ofollow_symlinks -oPreferredAuthentications=password -opassword_stdin
{e2c523ec-0706-48a8-bf42-86a0a9700b4e} cygfuse: initialization failed: winfsp-x86.dll not found
{e2c523ec-0706-48a8-bf42-86a0a9700b4e} exit 1
question: where I need to put this file to work in portable mode?
I don't want to install all components, I want to run it in portable mode, if it's possible to use relative path for sshfs.exe and for winfsp-x86.dll will be great!.
Thanks, best regards

**Comment by evsar3** [comment]
There is no portable version available for SSHFS-Win Manager, and, as far as I know, nor SSHFS-Win/WinFSP

In order to achieve what you want, you must port SSHFS-Win and WinFSP too.

**Comment by onlineapps-cloud** [comment]
I need option to change default path for winfsp-x86.dll, and all will work, ok

**Comment by evsar3** [comment]
WinFSP is a dependency of SSHFS-Win.

You may ask this question in https://github.com/billziss-gh/sshfs-win/issues

However, try put this DLL in the same folder as SSHFS-Win or SSHFS-Win\bin and registering it using regsvr32
