### ISSUE TITLE
Unable to select private key authentication method

### ISSUE THREAD

**Issue by nborisenkov** [evsar3/sshfs-win-manager#5]
When I try to select an authentication method for a new host (or while editing an existing host), I cannot select authentication by private key. It looks like these dropdown items are disabled.

Windows 10 1909
sshfs-win-manager: 1.0.0

**Comment by evsar3** [comment]
As mentioned in our README, unfortunately only password-based authentication is available for now. It should be available in 1.0.1.

**Comment by nborisenkov** [comment]
Sorry, I did not carefully read the README

**Comment by evsar3** [comment]
I'm working on it... it will be available today

**Comment by evsar3** [comment]
Key-based authentication is now available in [v1.0.1](https://github.com/evsar3/sshfs-win-manager/releases/tag/v1.0.1)
Enjoy!
