### ISSUE TITLE
[Feature Request] Automatic reconnect on startup

### ISSUE THREAD

**Issue by parlar** [evsar3/sshfs-win-manager#50]
I very much like sshfs-win-manager, thank you for creating it! I have really spent too many hours wrestling with smb ... Really nice also to be able to use private/public keys.

I notice, however, that "drives" are not reconnected if left mounted when the windows pc is rebooted. Is that by design? If I simply use sshfs-win (not manager) and map drive letters in explorer, I believe that the mounts are reconnected on reboot. That behaviour would be convenient.

Thought I should mention also that I ran into issue https://github.com/evsar3/sshfs-win-manager/issues/9 , all parts (winfsp, sshfs-win, sshfs-win-manager) freshly downloaded and installed just now.

**Comment by evsar3** [comment]
Feature implemented by @lancetekk 
Thank you by your PR. Appreciated.

Feature must be present in next release; scheduled to weekend.
