### ISSUE TITLE
Can't login to remote using public *.ppk file 

### ISSUE THREAD

**Issue by gszurek** [evsar3/sshfs-win-manager#52]
Hi,
In putty it works, but in SSHFS-WIN doesn't. I have "invalid format" error.

**Comment by evsar3** [comment]
You are using an incorrect key type. PPK only works in PuTTY, you need an OpenSSH key format.

Generate a new key using `ssh-keygen` or convert your existing PuTTY key to OpenSSH using `puttygen.exe` by open your PPK key, and then click at 'Conversions' then on 'Export OpenSSH Key'.

**Comment by MulverineX** [comment]
This isn't working for me
