### ISSUE TITLE
I want to use this app to connect to my android phone but...

### ISSUE THREAD

**Issue by imanmoghimiq30** [evsar3/sshfs-win-manager#55]
Hello 
Thank you for developing this GUI. I ran the shh server on my android phone, when I want to connect, it connects successfully but as you can see on my screen shoot I can't see my files.
///////debug note
![Screenshot (18)](https://user-images.githubusercontent.com/33248902/97781565-9f3a1300-1ba1-11eb-8dc3-50fd425d7048.png)

--------------------------------------------------------------------------------
date: 2020-10-31T14:10:53.880Z
conn: {294fb7af-8d23-42af-b49b-ba0a086a7fc6} (Note 4)
conntype: password
cmd: "C:\Program Files\SSHFS-Win\bin\sshfs.exe" root@10.0.0.3:/ E: -p2222 -ovolname=Note 4 -odebug -ologlevel=debug1 -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oidmap=user -ouid=-1 -ogid=-1 -oumask=000 -ocreate_umask=000 -omax_readahead=1GB -oallow_other -olarge_read -okernel_cache -ofollow_symlinks -oPreferredAuthentications=password -opassword_stdin
{294fb7af-8d23-42af-b49b-ba0a086a7fc6} stderr: SSHFS version 3.5.2
{294fb7af-8d23-42af-b49b-ba0a086a7fc6} stderr: executing <ssh> <-x> <-a> <-oClearAllForwardings=yes> <-oPort=2222> <-ologlevel=debug1> <-oStrictHostKeyChecking=no> <-oUserKnownHostsFile=/dev/null> <-oPreferredAuthentications=password> <
{294fb7af-8d23-42af-b49b-ba0a086a7fc6} stderr: -oNumberOfPasswordPrompts=1> <-2> <root@10.0.0.3> <-s> <sftp>
{294fb7af-8d23-42af-b49b-ba0a086a7fc6} stderr: debug1: Connecting to 10.0.0.3 [10.0.0.3] port 2222.
{294fb7af-8d23-42af-b49b-ba0a086a7fc6} stderr: debug1: Connection established.
{294fb7af-8d23-42af-b49b-ba0a086a7fc6} stderr: debug1: Remote protocol version 2.0, remote software version SSH Server - Banana Studio
debug1: no match: SSH Server - Banana Studio
debug1: Authenticating to 10.0.0.3:2222 as 'root'
{294fb7af-8d23-42af-b49b-ba0a086a7fc6} stderr: debug1: SSH2_MSG_KEXINIT sent
{294fb7af-8d23-42af-b49b-ba0a086a7fc6} stderr: debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: ecdh-sha2-nistp256
debug1: kex: host key algorithm: ssh-rsa
debug1: kex: server->client cipher: aes128-ctr MAC: hmac-sha2-256 compression: none
debug1: kex: client->server cipher: aes128-ctr MAC: hmac-sha2-256 compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
{294fb7af-8d23-42af-b49b-ba0a086a7fc6} stderr: debug1: Server host key: ssh-rsa SHA256:3mNL574rJyHCOGm1e7Upx4NHXMg/YnJJzq+jXhdQQxI
{294fb7af-8d23-42af-b49b-ba0a086a7fc6} stderr: debug1: Will attempt key: /cygdrive/c/Users/Iman/.ssh/id_xmss
{294fb7af-8d23-42af-b49b-ba0a086a7fc6} stderr: debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: password,keyboard-interactive
debug1: Next authentication method: password
{294fb7af-8d23-42af-b49b-ba0a086a7fc6} stderr: debug1: Authentication succeeded (password).
Authenticated to 10.0.0.3 ([10.0.0.3]:2222).
debug1: channel 0: new [client-session]
debug1: Entering interactive session.
debug1: pledge: network
{294fb7af-8d23-42af-b49b-ba0a086a7fc6} stderr: debug1: Sending subsystem: sftp
{294fb7af-8d23-42af-b49b-ba0a086a7fc6} stderr: Server version: 3
{294fb7af-8d23-42af-b49b-ba0a086a7fc6} stderr: failed to detect remote user ID
{294fb7af-8d23-42af-b49b-ba0a086a7fc6} stderr: The service sshfs has been started.

**Comment by evsar3** [comment]
Hello @imanmoghimiq30 

I've have tried this app with my Samsung Galaxy Note 10 and managed to successfully connect to my phone.

Make sure to add the "Path" folders to the user you setup on your phone.

Check this video:
https://photos.app.goo.gl/3bqejETsKuppvtJf7

Ater that, setup the connection into the Manager normally and it should works.

BTW awesome app, didn't knew it.
