### ISSUE TITLE
Enhancement request - private key with password and password for user

### ISSUE THREAD

**Issue by FedderSan** [evsar3/sshfs-win-manager#56]
Really nice looking app, but I do need the additional security feature of using private keys with password, and the user has a password at the same time.

So far it just errors out on the private key.

I cant see there are any guidelines for issues/requests, so please inform me, then I will correct the enhancement request

**Comment by evsar3** [comment]
As discussed in #12, #27 and https://github.com/billziss-gh/sshfs-win/issues/217, its currently not possible to use a password protected key with SSHFS without using a 3rd party key agent. This setup is very complicated to be made and may not be an option too soon.

**Comment by breisig** [comment]
We need this feature badly
