### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by RSKothari** [evsar3/sshfs-win-manager#6]
1. Option to minimize GUI. It just remains maximized all the time.
2. Collect stats about connections dropped and provide to user.

**Comment by evsar3** [comment]
Hello @RSKothari, thank you for the suggestions.

> 1. Option to minimize GUI. It just remains maximized all the time.
This feature actually already exists, if you close the window, it actually still running in background in the system tray.
![System tray](https://c.servers.babum.dev/static/sshfs-win-manager/systray-screenshot.png) 

> 2. Collect stats about connections dropped and provide to user.
This is a good suggestion however there is no plan to implement such feature. For now the priority is to make the program stable and implement other authentication methods. I will let you know thought this issue when something like this is implemented.

Thank you.

**Comment by RSKothari** [comment]
Thanks @evsar3 because the first observation is how rapidly the connection keeps getting.
