### ISSUE TITLE
Profile autoconnect suggestion

### ISSUE THREAD

**Issue by binarweb** [evsar3/sshfs-win-manager#62]
Hi guys!
I want to say that this is an amazing SSH frontend, I've been waiting for a long time for someone to create this. I know there was [win-sshfs](https://code.google.com/archive/p/win-sshfs/), but it had some issues and no one is maintaning it anymore.

I would like to suggest a feature: to have an autoconnect option for each profile when the program starts.

**Comment by evsar3** [comment]
Hi @binarweb I've have been using the win-sshfs for a long time before creating this project and it was a truly inspiration for me. The feature you requested already has been implemented in PR #53 by @lancetekk and must be present in next stable release scheduled for later this month.

**Comment by binarweb** [comment]
I just saw this. By default, when I click the issues, they are filtered and I didn't see the other issues until I cleared the filter.

I just donated 5 USD. Thanks!

**Comment by evsar3** [comment]
Thank you for your donation! The children they will receive your donation are certainly grateful.

I wish more people contribute, I just received 10 USD past 60 days.
