### ISSUE TITLE
[Feature request] Auto-reconnect on connection failure

### ISSUE THREAD

**Issue by jackmawer** [evsar3/sshfs-win-manager#64]
It would be really useful if the program automatically tried to reconnect to a server if the connection fails. For me, this would be useful as when I hibernate my computer or my network adapter stops working, I have to manually restart the connection from the GUI.

**Comment by fabeit** [comment]
In the advanced parameters I have set "recconect" but it doesn't seem to work all the time, give it a try. There should also be a way to set ServerAliveInterval
