### ISSUE TITLE
The connect icon does nothing and it cannot be debugged.

### ISSUE THREAD

**Issue by JosephLucas** [evsar3/sshfs-win-manager#73]
Hi, thanks for sshfs-win-manager !
A client with a Windows OS cannot connect a remote folder. 
When he clicks on the connect icon, nothing happens.
Everything is configured exactly as on my reference windows (in a VM), where this configuration does work properly.
On the client OS I enabled the debug log, but it displays nothing when he clicks on the connect icon.
Interestingly, my client can connect to the host machine with ssh, he has the appropriate rights on the mounted folder and he can mount the folder with sshfs-win.

What could be the issue here ?
Could you display more debug info about what happens when there is a click on the connect icon ?

**Comment by evsar3** [comment]
It looks like an environment related problem.

To debug issues like this only with building the source yourself. If you are an experienced JavaScript and Node.js programmer its a peace of cake.

This issue (https://github.com/evsar3/sshfs-win-manager/issues/43#issuecomment-688578976) has instructions on how to build the source.

**Comment by JosephLucas** [comment]
Thanks

> If you are an experienced JavaScript and Node.js programmer its a peace of cake.

That is unfortunately not my case. Furthermore i do not have access to the client machine. 
Any guess about what could be the environment cause ?

**Comment by evsar3** [comment]
Did you already tried to make a clean install of both, SSHFS-Win and SSHFS-Win Manager?
Make sure to remove the folders from `%AppData%` too.
Reboot your system, then try installing everything again.

**Comment by JosephLucas** [comment]
Thanks. Would it be of any help to reinstall WinFsp too ? Or can he overlook this.
I will tell him to try your solution.
