### ISSUE TITLE
Has problem with connect Non English charset in connection part.

### ISSUE THREAD

**Issue by writingdeveloper** [evsar3/sshfs-win-manager#76]
I have some problem in connection part with charset. 

Drive name works fine any kinds of charsets. (ex: English, Korean, Chinese, Japanese...)

But in username text-box it can only use English charset. I tested several charsets like Korean, Chinese, and Japanese and it doesn't work.
We use Korean username (Windows OS Env) before and with win-sshfs  and network drive connect function It works fine.  But  sshfs-win-manager looks fine and it seems more user friendly so We decide to use sshfs-win-manager.

After that we moved all the data in synology and create all the username in English. So we thought the charset problem has been solved temporarily. But the problem is coming from other side.

It's from server directory text-box . Before we use root directory name like 'SSHFS-Server' so there is no problem with connection . And even in 'SSHFS-Server' Folder there are many Non English charset files and folder, it works fine.
But When we tried to add Korean(Japanese, Chinese) language in directory (ex /SSHFS-Server/포도당 Folder/) it shows 'Error; Invalid user name or password'

And I found that in CMD, When I use Non English Charset, there are " charset is added in username

Ex) In English Directory
debug1: Authenticating to cloud.stpsystem.co.kr:22 as 'myusername'
Ex) Add Non English charset in Directory
debug1: Authenticating to cloud.stpsystem.co.kr:22 as '"myusername'

![image](https://user-images.githubusercontent.com/6832586/109411371-f54e8400-79e4-11eb-9664-25c8fa80f6cb.png)

Is there anyways to solve this problem?

**Comment by evsar3** [comment]
In theory the Electron must take care of Unicode charset by itself.
Must be a bug on encoding the JSON, I'll take a look into it this weekend.

**Comment by evsar3** [comment]
It would be appreciated if you can provide the log of the connection.

Enable the log on **Settings** > **Show Debug Panel**

Be sure to remove any sensitive data from the log before posting it.
