### ISSUE TITLE
Issue with Thunderbird and Outlook

### ISSUE THREAD

**Issue by OrisysAU** [evsar3/sshfs-win-manager#77]
Hi, I seem to have come across an issue when trying to save a file attachment (from within either Outllook or Thunderbird) directly to the mapped drive. Everything else works just fine and I can move files from the local drive to the mapped drive using explorer no probs at all.

When trying to save with Outlook or Thunderbird (direct to mapped drive) nothing happens, it seems like it has worked withno error or anything but if you open explorer and look at the  map drive where it was supposed to be saved, the file is not there.

I have been able to replicate this problem at a clients premises, at my own network and a friend has also confirmed the problem.
This may not be an issue with the manager, it may be associated with win-sshfs.. I also have installed all the latest versions of WinFsp and SSHFS-Win.. Any thoughts ?

With thanks..

**Comment by evsar3** [comment]
As you said, this must be related to SSHFS-Win or WinFSP. In this case, better find help on those repositories.

SSHFS-Win:
https://github.com/billziss-gh/sshfs-win
