### ISSUE TITLE
bug ? "incorrect username" when trying to login with key BUT works with password

### ISSUE THREAD

**Issue by seccentral** [evsar3/sshfs-win-manager#78]
Like the title said. 
I'd love to provide logs but I don't know where they're kept if they're kept.
Obviously unusable on systems with "PasswordAuthentication no"

**Comment by evsar3** [comment]
Enable connection log on **Settings** > **Show Debug Panel**

Be sure to remove any sensitive information from the logs before posting.

**Comment by seccentral** [comment]
> Enable connection log on **Settings** > **Show Debug Panel**
> 
> Be sure to remove any sensitive information from the logs before posting.

I know that much myself, problem is there's nothing much there. 
here's all it said: 

```
--------------------------------------------------------------------------------
date: 2021-03-03T16:43:10.610Z
conntype: key-file
```
that's all 

and this popup error on the screen : 
![Untitled](https://user-images.githubusercontent.com/3766320/109840329-aefd5d00-7c50-11eb-9df9-34851a2707f1.png)

**Comment by evsar3** [comment]
Is your private key password protected? If it is the case, its not supported.

**Comment by seccentral** [comment]
Well, i guess that's that.
Regardless, this needs to be reflected in the error message. What's my username got to do with it ? It's perfectly valid. 
Can you please update the error with a proper description in the next release ?
