### ISSUE TITLE
Meet problem:"a javascript error occurred in the main process"

### ISSUE THREAD

**Issue by ouyangjianbo** [evsar3/sshfs-win-manager#80]
![x](https://user-images.githubusercontent.com/40689365/110078682-120f0100-7dc3-11eb-95eb-a6dddb7921de.JPG)
I met this problem after using the software.
After I re-install the software， the software goes well. 
But after several hours, the problem come up again. 
Could you help me to solve this problem?
Thanks！

**Comment by YuShenLu** [comment]
I have the same problem. also when trying to quit the software I get 
![image](https://user-images.githubusercontent.com/44778814/110372325-2ac62380-801c-11eb-9099-7e7b6512cb98.png)

**Comment by ouyangjianbo** [comment]
> I have the same problem. also when trying to quit the software I get
> ![image](https://user-images.githubusercontent.com/44778814/110372325-2ac62380-801c-11eb-9099-7e7b6512cb98.png)
> 
> It seems I can temporarily fix this by end process and restart it, but this keeps coming back

Right. The problem keeps coming back.

**Comment by ctheunie** [comment]
Hi I also have this same error when the system has been idle for a short while

**Comment by lawrenceamadi** [comment]
Hi, I've also encountered this issue a number of times when my system has been running for an extended period. 
Restarting the system fixes it, but is inconvenient.
![image](https://user-images.githubusercontent.com/84790473/199150073-94087603-68a9-45e1-ba65-b56555ac1209.png)

**Comment by joacchino** [comment]
try deleting the cache files under %appdata%\SSHFS-Win Manager

helped for me as a workaround instead of restarting the system

**Comment by TimSchim** [comment]
As another workaround, stopping the SSHFS-Win Manager task from the Task-Manager worked for me too. Getting the same error as others when trying to stop normally.
