### ISSUE TITLE
IMPOSSIBLE CREATE/MOVE/MODIFY EVERYTHING

### ISSUE THREAD

**Issue by vincenzogianfelice** [evsar3/sshfs-win-manager#84]
Hi. I tried to mount my pc with linux (debian) from win 10. Once assembled and opened I can practically do nothing!
Why?

Thank you

**Comment by evsar3** [comment]
It depends on a lot of things... you server configuration, the user/group permissions, the mask options... etc.
Try reading some stackoverflow question and see if you find anyone that may help you. I just can guide you to this point.
Good luck.
