### ISSUE TITLE
[Feature request] Mount to the first available drive letter

### ISSUE THREAD

**Issue by darkguy2008** [evsar3/sshfs-win-manager#85]
Hi!

Thanks for this awesome project, it's been a lifesaver!

I have a small suggestion: I find myself connecting to more than 1 server at a time, so I'd like to see if it's possible to make the connections automount (like what happens when you plug in an USB drive) so I don't have to keep changing the drive letters when I'm already connected to a server and need to reach another one.

Thanks again!

**Comment by darkguy2008** [comment]
@evsar3 any reason why it's in wontfix now? I don't think I asked for something crazy, this is a real use case and it's really cumbersome to be switching the drive letter of the SSH server I want to connect to if I have another device using that letter.

If you need any help, I could even write a PR if you want. But closing them as wontfix without specifying a valid reason is a tad unpolite...

**Comment by evsar3** [comment]
Seems to be an overkill feature for something that can be easily avoided with a bit of connection management.

Why don't you just set different drive letters for your connections? This way you will never get drive letter collisions. I personally use Z, Y, X, W, etc for my connections.

**Comment by evsar3** [comment]
Seems to be an overkill feature for something that can be easily avoided with a bit of connection management.

Why don't you just set different drive letters for your connections? This way you will never get drive letter collisions. I personally use Z, Y, X, W, etc for my connections.

**Comment by darkguy2008** [comment]
> Seems to be an overkill feature for something that can be easily avoided with a bit of connection management.
> 
> Why don't you just set different drive letters for your connections? This way you will never get drive letter collisions. I personally use Z, Y, X, W, etc for my connections.

Qell it may be overkill for **you** but it's definitely an UX improvement for **me**.

Well, all is good as long as I don't put an USB drive, and I work with them a lot, plus I also connect to different servers every now and then. When I happen to have an USB drive plugged in and I want to connect to a server, OR if I want to connect to two or more servers **at the same time** then I have to set up each server with a different letter. My SSH config file has around 30+ or so servers, and while I'm not connected to each one of them all the time, it's greatly appreciated if the app itself can (and it definitely can) connect using the closest free drive letter, just like Windows does when plugging an USB drive.

It's merely an UX improvement that would've been appreciated. Something that's not an use case for you might be for another user, and just closing feature requests like this just because you think it's overkill doesn't make much sense, honestly.

**Comment by evsar3** [comment]
I would be happy to merge a PR with this implementation.

**Comment by evsar3** [comment]
Please, download the latest beta version https://github.com/evsar3/sshfs-win-manager/releases/tag/v1.3.0-beta.1 and provide some feedback, please.

**Comment by evsar3** [comment]
To enable automatic drive letter assignment, instead of choosing a drive letter, select `Auto` on the drive letter list.
