### ISSUE TITLE
[Feature request] Add support to keep alive feature

### ISSUE THREAD

**Issue by AnnAngela** [evsar3/sshfs-win-manager#89]
Many tool, such as XShell, have features to *send keep alive messages while session lives* and *send TCP keep alive packet while network idles*, and I really hope that this tool can support these feature(because that if i left computer for a while it will be disconnected).
Please add support to it, or let me know if I need to open this issue in other project.

**Comment by akiledal** [comment]
I think the `reconnect` option would solve your disconnection issue, which is accessible in the `advanced` tab in edit mode. However, enabling custom command line parameters disables all the default options (2597062d9c81f9c803ab94a3806b3feb76f0aec7), so if you set reconnect you might need to set others, too (for example, I was getting permission problems until I realized this). @evsar3  would it be possible to have either a toggle just for reconnect, like `connect on startup` or an option to keep default parameters in addition to any custom ones?

**Comment by evsar3** [comment]
> I'm actually not sure it's currently possible with the gui to recreate all the default options and add `reconnect`, because the window is not scrollable or resizable and the list gets too long.

This was reported on #89 but I have to say that I'm quite busy to work on this project now. I will try to take a look at this weekend. 

The toggle for `reconnect` option is totally possible.

**Comment by evsar3** [comment]
The latest beta version https://github.com/evsar3/sshfs-win-manager/releases/tag/v1.3.0-beta.1 has a switch for the reconnect option.
I'm also thinking in add another switch to toggle with the default options should be cleared or not on using custom params.

Feedback, please.

**Comment by AnnAngela** [comment]
> The latest beta version https://github.com/evsar3/sshfs-win-manager/releases/tag/v1.3.0-beta.1 has a switch for the reconnect option and the bug with the long list of params was also fixed.
> I'm also thinking in add another switch to toggle if the default options should be cleared or not on using custom params.
> 
> Feedback, please.

THX A LOT! I have tried this beta version, and reconnect option work just fine and nice, looks really good to me!
