### ISSUE TITLE
Is there any ways to set drive capacity?

### ISSUE THREAD

**Issue by writingdeveloper** [evsar3/sshfs-win-manager#94]
There are a lots of Advanced setting in 'Advanced' tab. I though there are custom command and params to set disk's capacity.

Is there any ways to set drive capacity? My storage is 14TB but my system's root volume is only 4~5GB so I cannot upload over 4~5GB files because in local drive it's capacity is set 5GB storage like image.

![image](https://user-images.githubusercontent.com/6832586/116528619-03eae600-a917-11eb-820f-ef35292ef57c.png)

**Comment by evsar3** [comment]
Hello,

I'm not aware of any SSHFS option that can be used for setting the disk size.

Note that the options on the advanced tab, is the options supported by the official SSHFS protocol.

SSHFS man page can be found here:
https://linux.die.net/man/1/sshfs
