### ISSUE TITLE
Feature request - Add "ciphers" option

### ISSUE THREAD

**Issue by JoseMMerida** [evsar3/sshfs-win-manager#97]
Hi,

I think that adding the option to change the cipher would be cool. To make it easier the field of the cipher should be introduced manually, I think.

Very nice application!

**Comment by evsar3** [comment]
Can you provide some docs on 'ciphers' option?

You can also create a PR yourself.
The file that holds the options is https://github.com/evsar3/sshfs-win-manager/blob/master/src/renderer/SshfsParamsList.js

Thank you.

**Comment by JoseMMerida** [comment]
#101
